spring:
  application:
    name: DocumentForKafka
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    sendSizeMessage: "10485880"

folder:
  path: ${PATH}

logging:
  file:
    name: ${FILE_LOGS}
  pattern:
    rolling-file-name: ${ROLLING_FILE_NAME}

cron_job: ${CRON_JOB}

topic:
  name: ${TOPIC_NAME}

topics:
  topics-mapping:
    BILL: BILL
    INVENTORY: INVENTORY
    OrderStatus: ORDER-STATUS

basket:
  path: ${BASKET_PATH}